### ISSUE TITLE
503 Service Unavailable 

### ISSUE THREAD

**Issue by Temiogundeji** [dawahanigeria-team/rayyan-server#10]
Login and Registration Endpoints returning service unavailable. 
I tested it with postman and one other browser based REST CLIENT.

**Comment by Temiogundeji** [comment]
I've moved on though, while I await a fix.
@Yusadolat

**Comment by Yusadolat** [comment]
Okay, I will check right away. Heroku might be smoking weed

**Comment by Yusadolat** [comment]
![Screen Shot 2021-04-09 at 5 48 31 PM](https://user-images.githubusercontent.com/10975011/114214116-d20be280-995b-11eb-96e4-25235a63c1ce.png)


It working oooo

**Comment by Temiogundeji** [comment]
Its now working here too!

**Comment by Yusadolat** [comment]
Heroku is high on Drugs.Pele
