### ISSUE TITLE
Fast API not working properly

### ISSUE THREAD

**Issue by Temiogundeji** [dawahanigeria-team/rayyan-server#12]
The endpoint isn't behaving properly. 
{
  "message": "Wowza, Server is up!"
}

This is what I get for every request to given endpoints.

@Yusadolat

**Comment by Yusadolat** [comment]
Screenshot please???

Is this happening on every endpoints?

**Comment by Temiogundeji** [comment]
Yes!
![Response Anomaly](https://user-images.githubusercontent.com/28397005/115228055-259dcf00-a0c6-11eb-9104-9b6937d6ea06.PNG)

add Fast,  getOne Fast, get Fasts All returns this.

**Comment by Temiogundeji** [comment]
![getSingleFast](https://user-images.githubusercontent.com/28397005/115228453-a52b9e00-a0c6-11eb-95cb-6c7a05f9f1ef.PNG)

getSingleFast

**Comment by Yusadolat** [comment]
Are you sure you check the Documentation???

1. Single Fast require fast ID
2. You are to send a JSON not URL encoded data
![Screen Shot 2021-04-19 at 12 23 15 PM](https://user-images.githubusercontent.com/10975011/115228716-06289580-a10a-11eb-92dd-d3b9b2c34d02.png)

**Comment by Temiogundeji** [comment]
Is this request body not correct?
``
{
    "name": "Rajab",
    "description": "A fast in the month of Rajab"
}
``

**Comment by Yusadolat** [comment]
It's Correct as JSON

**Comment by Temiogundeji** [comment]
But, when I tried to add fast, it is not working properly. Using that same body.

**Comment by Yusadolat** [comment]
What's the response?

**Comment by Temiogundeji** [comment]
![Capturerree](https://user-images.githubusercontent.com/28397005/115235896-8d0c4c80-a0cf-11eb-9ed4-13785d234ef2.PNG)

**Comment by Yusadolat** [comment]
![Screen Shot 2021-04-19 at 2 01 51 PM](https://user-images.githubusercontent.com/10975011/115240591-ce284f00-a117-11eb-92d1-a772d3b221e0.png)
@Temiogundeji this is how the response should look like..

**Comment by Temiogundeji** [comment]
> 
> 
> ![Screen Shot 2021-04-19 at 2 01 51 PM](https://user-images.githubusercontent.com/10975011/115240591-ce284f00-a117-11eb-92d1-a772d3b221e0.png)
> @Temiogundeji this is how the response should look like..

I don't know why I'm getting something different. You can see that I follow the instructions this time around.

**Comment by Temiogundeji** [comment]
It now worked... When I used Advanced REST Client. and 

It worked here too:

https://hoppscotch.io/?method=POST&url=https://rayyan-server.herokuapp.com&path=/api/fasts&contentType=application/json&params=%5B%7B%22key%22:%22%22,%22value%22:%22%22,%22type%22:%22query%22,%22active%22:true%7D%5D&bodyParams=%5B%7B%22key%22:%22name%22,%22value%22:%22Ramadan%2010%22,%22active%22:true%7D,%7B%22key%22:%22description%22,%22value%22:%22Ramadan%20is%2010.%22,%22active%22:true%7D%5D

**Comment by Yusadolat** [comment]
> It now worked... When I used Advanced REST Client. and
> 
> It worked here too:
> 
> https://hoppscotch.io/?method=POST&url=https://rayyan-server.herokuapp.com&path=/api/fasts&contentType=application/json&params=%5B%7B%22key%22:%22%22,%22value%22:%22%22,%22type%22:%22query%22,%22active%22:true%7D%5D&bodyParams=%5B%7B%22key%22:%22name%22,%22value%22:%22Ramadan%2010%22,%22active%22:true%7D,%7B%22key%22:%22description%22,%22value%22:%22Ramadan%20is%2010.%22,%22active%22:true%7D%5D

You and your Postman needs Cane faa

**Comment by Temiogundeji** [comment]
> 
> 
> > It now worked... When I used Advanced REST Client. and
> > It worked here too:
> > https://hoppscotch.io/?method=POST&url=https://rayyan-server.herokuapp.com&path=/api/fasts&contentType=application/json&params=%5B%7B%22key%22:%22%22,%22value%22:%22%22,%22type%22:%22query%22,%22active%22:true%7D%5D&bodyParams=%5B%7B%22key%22:%22name%22,%22value%22:%22Ramadan%2010%22,%22active%22:true%7D,%7B%22key%22:%22description%22,%22value%22:%22Ramadan%20is%2010.%22,%22active%22:true%7D%5D
> 
> You and your Postman needs Cane faa

I'll stop testing with it for now. I'm fed up.
