### ISSUE TITLE
Add Bulk Fast issue

### ISSUE THREAD

**Issue by Temiogundeji** [dawahanigeria-team/rayyan-server#19]
Add Bulk isn't working as expected. 

Request Body
{
    "number": 3,
    "description": "I no chop sahur",
    "user": "6083279d963c7c2cbc77db11"
}

Response
{
  "message": "Wowza, Server is up!"
}

**Comment by Yusadolat** [comment]
Oh, I see, continue with the UI seems Heroku needs me to fix something here.

**Comment by Temiogundeji** [comment]
Alright Bro!

**Comment by Yusadolat** [comment]
@Temiogundeji 
Please now. Below is the Screenshot
![Screen Shot 2021-05-09 at 2 12 20 PM](https://user-images.githubusercontent.com/10975011/117573579-95edae00-b0d0-11eb-929d-dd27891c5ade.png)

**Comment by Temiogundeji** [comment]
Yes! It worked!
