### ISSUE TITLE
500 Internal server error returned

### ISSUE THREAD

**Issue by Temiogundeji** [dawahanigeria-team/rayyan-server#4]
Request:
{
    "success": false,
    "error": "celebrate request validation failed"
}

Response:
{
    "firstName": "Olayinka",
    "lastName": "Abdulhamid",
    "email": "olayinkaabdulhamid@gmail.com",
    "password": "olayinkaabdulhamid"
}

@Yusadolat Please look into this.

**Comment by Yusadolat** [comment]
On creating new user right?

**Comment by Yusadolat** [comment]
![Screen Shot 2021-04-06 at 10 43 20 AM](https://user-images.githubusercontent.com/10975011/113692141-23e70b00-96c5-11eb-9527-ccbcbd6f4bc7.png)
I just did a test request now and it working fine...

**Comment by Yusadolat** [comment]
Oh, I see where the issue is. I set the password range from 8 -15 Characters

@Temiogundeji

**Comment by Temiogundeji** [comment]
Good!

**Comment by Yusadolat** [comment]
Lemme know if you have any other issues

**Comment by Temiogundeji** [comment]
I tried the endpoint on another rest client it still didn't work. It worked throughout yesterday.

**Comment by Yusadolat** [comment]
> I tried the endpoint on another rest client it still didn't work.

Intresting..
Can you Provide the screenshot?
What's the name of the REST client. I will download to see if I can reproduce the error

**Comment by Temiogundeji** [comment]
![error](https://user-images.githubusercontent.com/28397005/113696453-e2d00600-9686-11eb-8443-8ca20bd084f9.PNG)

Advanced REST Client

**Comment by Yusadolat** [comment]
Checking...

**Comment by Temiogundeji** [comment]
https://rayyan-server.herokuapp.com/api/auth/register

Hope this isn't wrong.

**Comment by Yusadolat** [comment]
> https://rayyan-server.herokuapp.com/api/auth/register
> 
> Hope this isn't wrong.

This is correct..

Meanwhile, I don't use chrome I can't reproduce the error since you are using a chrome extension.

**Comment by Temiogundeji** [comment]
The error still persist in POSTMAN too

**Comment by Temiogundeji** [comment]
![Capture](https://user-images.githubusercontent.com/28397005/113697367-f2038380-9687-11eb-9a6f-99f7e3e9e4aa.PNG)

**Comment by Yusadolat** [comment]
> The error still persist in POSTMAN too

LOL
You need to do a lot of Istigifarr
![Screen Shot 2021-04-06 at 11 27 31 AM](https://user-images.githubusercontent.com/10975011/113697442-17fe4780-96cb-11eb-868e-748534a0fe32.png)

**Comment by Yusadolat** [comment]
Bros that's an online REST client ooo

https://hoppscotch.io/?method=POST&url=https://rayyan-server.herokuapp.com&path=/api/auth/register&contentType=application/json&bodyParams=%5B%7B%22key%22:%22firstName%22,%22value%22:%22Ola%22,%22active%22:true%7D,%7B%22key%22:%22lastName%22,%22value%22:%22Ade%22,%22active%22:true%7D,%7B%22key%22:%22email%22,%22value%22:%22yu@gmail.com%22,%22active%22:true%7D,%7B%22key%22:%22password%22,%22value%22:%22%22,%22active%22:true%7D%5D

**Comment by Temiogundeji** [comment]
![Screenshot_2021-04-06 Hoppscotch - Open source API development ecosystem](https://user-images.githubusercontent.com/28397005/113698160-02682e00-9689-11eb-923c-a37d48ee7edd.png)

Wallohi I really Istigfar.

**Comment by Yusadolat** [comment]
Can we jump on a quick call?

**Comment by Temiogundeji** [comment]
``
Object {
  "message": "Wowza, Server is up!",
}
``

Right from VSCode console.

**Comment by Yusadolat** [comment]
> `Object { "message": "Wowza, Server is up!", }`
> 
> Right from VSCode console.

Correct, When you call the ROOT endpoint!

**Comment by Temiogundeji** [comment]
Meaning it works!

**Comment by Temiogundeji** [comment]
The contradiction is still surprising.

**Comment by Yusadolat** [comment]
Call the /auth/register let see

**Comment by Temiogundeji** [comment]
``
Object {
  "error": "celebrate request validation failed",
  "success": false,
}
``

Same as the one return in postman

**Comment by Temiogundeji** [comment]
https://stackoverflow.com/questions/64205565/why-did-celebrate-request-validation-failed

I tried to make research on the error.

**Comment by Yusadolat** [comment]
#6

**Comment by Yusadolat** [comment]
Retry it now please @Temiogundeji

**Comment by Temiogundeji** [comment]
Ok!
It worked!
