### ISSUE TITLE
Handling social auth.

### ISSUE THREAD

**Issue by Temiogundeji** [dawahanigeria-team/rayyan-server#7]
I tried to use the endpoint (https://rayyan-server.herokuapp.com/api/auth/facebook) provided for the social auth, it just returned this response: 
``
{
  "message": "Wowza, Server is up!"
}
``
Should I follow the normal expo style or is there anything I'm missing?

**Comment by Yusadolat** [comment]
GET /api/auth/google - Login with google
POST /api/auth/facebook - Login with facebook
GET /api/auth/google/callback - Callback route for google auth to redirect to
GET /api/auth/facebook/callback - Callback route for facebook auth to redirect to

This endpoint???

**Comment by Yusadolat** [comment]
You can leave the Social auth to the other pages anyways

**Comment by Temiogundeji** [comment]
{ "message": "Wowza, Server is up!" }

I have no experience within apps, so I want to learn.

**Comment by Temiogundeji** [comment]
Please explain the flow.

**Comment by Temiogundeji** [comment]
> 
> 
> You can leave the Social auth to the other pages anyways

I feel I should learn it, don't think its hard bro!

The response it returned is not different from the one gotten when testing the main endpoint.

**Comment by Yusadolat** [comment]
We'll come back to it. It requires creating a developer's account which might take time. I used my account for the backend test. Let move the home screen so we can finish soon.
